---
apiVersion: v1
kind: ConfigMap
metadata:
    name: metabase-configmap
data:
  MB_DB_TYPE: 'postgres'
  MB_DB_DBNAME: {{ .Values.dba.database }}
  MB_DB_PORT: {{ .Values.dba.port }}
  MB_DB_HOST: {{ .Values.dba.host }}
...
